spring.datasource.url=jdbc:postgresql://dpg-d6t0tf5m5p6s73b3ouug-a.frankfurt-postgres.render.com/finance_tracker_jd18
spring.datasource.username=finance_tracker_jd18_user
spring.datasource.password=1QxcBibHA1o4gBcvMLZsFevk2GkioG2g

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update